title: My docs
description: An awesome docs project
permalink: pretty
search_enabled: true
color_scheme: dark

theme: just-the-docs

#remote_theme: pmarsceill/just-the-docs
#plugins:
#  - jekyll-remote-theme
